### ISSUE TITLE
How can I i

### ISSUE THREAD

**Issue by Kudo38** [kernel-dev/HonkaiStarRailFPSUnlock#2]
How can I deinstall the fps cap or disable it? It corrupts the graphics settings

**Comment by kernel-dev** [comment]
Well, you can just go into the Graphics settings and choose FPS and set it to 60 or what-not, and it'll bring back the settings. After restarting the game, it should go back to 60FPS.

You could also delete the registry value manually (it's under `Computer\HKEY_CURRENT_USER\SOFTWARE\Cognosphere\Star Rail`, and the value is `GraphicsSettings_Model_hXXXXXXXXXX`). So simply delete the value, and restart the game. Might need a 2nd restart, so take note. __If this alone doesn't work, try verifying file integrity after deleting the value.__

I'm not sure why it borks the settings page in-game, it happens for me, too. But I simply set the graphics settings to the desired values before uncapping the FPS. Alternatively, you can also change the graphics settings through the registry editor (or even the program if you want to look at `unlocker/core/registry.py` and alter the config values there, but you would have to remove [these LoC](https://github.com/kernel-dev/HonkaiStarRailFPSUnlock/blob/main/unlocker/core/registry.py#L70-L76), because they copy over the current settings of the game you've adjusted).

I suppose the only way around this is to do a proper RAM patch, but that's very much bannable without a doubt.

However, I will be looking into this further, and hopefully adding an option to also revert the patch if possible.

**Comment by Kudo38** [comment]
Thank you for your quick and extremely detailed response! 
I use a fps uncapper on genshin too. Since like 2years. 
But as you said there might be a chance to get banned or caught in what anyway it is. So I only wanted to test it since its like new. Setting in manually to 60fps in the graphics settings works. Thanks again!

**Comment by kernel-dev** [comment]
As I mentioned in the README of this project, setting the value to anything above 120FPS simply makes it default back to rendering at 60FPS. 

My speculation is that, because the game is also available on iOS, and they provide iOS users--with a 120Hz display device--the ability to render at 120FPS, that the engine accepts (by default) 120FPS if you somehow manage to set it to that. Anything above that most likely requires a RAM patch (like for Genshin Impact). As such, I don't for certain know whether or not this is bannable, but I wouldn't think so, since you're not messing with anything low-level.

However, regarding Genshin Impact's situation, I've heard that their in-house AC has been disabled for quite some time now, due to false bans.
